ROMNAME   := starshard_cove
ROM_TITLE := "Starshard Cove"
USE_T3D   := 1

include ../../common/lesson.mk

# Capstone high-score save (L38). After n64.mk default is applied by lesson.mk.
N64_ROM_SAVETYPE := eeprom4k
