ROMNAME   := l38_save
ROM_TITLE := "L38 Save"

include ../../common/lesson.mk

# Advertise 4 Kibit EEPROM to Ares / flashcarts (advanced homebrew header).
# Must be set after lesson.mk includes n64.mk (that file defaults SAVETYPE empty).
N64_ROM_SAVETYPE := eeprom4k
